-- Seed data for States, Counties, and Municipalities
-- Run this after add_states_counties_municipalities.sql

-- Insert Florida state
INSERT INTO states (code, name) VALUES ('FL', 'Florida')
ON CONFLICT (code) DO NOTHING;

-- Insert all 67 Florida counties with their codes
INSERT INTO counties (state_id, code, name) 
SELECT s.id, c.code, c.name
FROM states s
CROSS JOIN (VALUES
    ('11', 'Alachua'),
    ('12', 'Baker'),
    ('13', 'Bay'),
    ('14', 'Bradford'),
    ('15', 'Brevard'),
    ('16', 'Broward'),
    ('17', 'Calhoun'),
    ('18', 'Charlotte'),
    ('19', 'Citrus'),
    ('20', 'Clay'),
    ('21', 'Collier'),
    ('22', 'Columbia'),
    ('23', 'Dade'),
    ('24', 'DeSoto'),
    ('25', 'Dixie'),
    ('26', 'Duval'),
    ('27', 'Escambia'),
    ('28', 'Flagler'),
    ('29', 'Franklin'),
    ('30', 'Gadsden'),
    ('31', 'Gilchrist'),
    ('32', 'Glades'),
    ('33', 'Gulf'),
    ('34', 'Hamilton'),
    ('35', 'Hardee'),
    ('36', 'Hendry'),
    ('37', 'Hernando'),
    ('38', 'Highlands'),
    ('39', 'Hillsborough'),
    ('40', 'Holmes'),
    ('41', 'Indian River'),
    ('42', 'Jackson'),
    ('43', 'Jefferson'),
    ('44', 'Lafayette'),
    ('45', 'Lake'),
    ('46', 'Lee'),
    ('47', 'Leon'),
    ('48', 'Levy'),
    ('49', 'Liberty'),
    ('50', 'Madison'),
    ('51', 'Manatee'),
    ('52', 'Marion'),
    ('53', 'Martin'),
    ('54', 'Monroe'),
    ('55', 'Nassau'),
    ('56', 'Okaloosa'),
    ('57', 'Okeechobee'),
    ('58', 'Orange'),
    ('59', 'Osceola'),
    ('60', 'Palm Beach'),
    ('61', 'Pasco'),
    ('62', 'Pinellas'),
    ('63', 'Polk'),
    ('64', 'Putnam'),
    ('65', 'St. Johns'),
    ('66', 'St. Lucie'),
    ('67', 'Santa Rosa'),
    ('68', 'Sarasota'),
    ('69', 'Seminole'),
    ('70', 'Sumter'),
    ('71', 'Suwannee'),
    ('72', 'Taylor'),
    ('73', 'Union'),
    ('74', 'Volusia'),
    ('75', 'Wakulla'),
    ('76', 'Walton'),
    ('77', 'Washington')
) AS c(code, name)
WHERE s.code = 'FL'
ON CONFLICT (state_id, code) DO NOTHING;

-- Insert all Florida municipalities
INSERT INTO municipalities (state_id, name)
SELECT s.id, m.name
FROM states s
CROSS JOIN (VALUES
    ('Alachua'),
    ('Altamonte Springs'),
    ('Anna Maria'),
    ('Apalachicola'),
    ('Apopka'),
    ('Arcadia'),
    ('Archer'),
    ('Astalula'),
    ('Atlantic Beach'),
    ('Atlantis'),
    ('Auburndale'),
    ('Aventura'),
    ('Avon Park'),
    ('Bal Harbour'),
    ('Baldwin'),
    ('Bartow'),
    ('Bay Harbor Islands'),
    ('Bay Lake'),
    ('Bell'),
    ('Belle Glade'),
    ('Belle Isle'),
    ('Belleair'),
    ('Belleair Beach'),
    ('Belleair Bluffs'),
    ('Belleair Shore'),
    ('Belleview'),
    ('Beverley Beach'),
    ('Biscayne Park'),
    ('Blountstown'),
    ('Boca Raton'),
    ('Boynton Beach'),
    ('Bradenton'),
    ('Bradenton Beach'),
    ('Branford'),
    ('Bristol'),
    ('Bronson'),
    ('Brooker'),
    ('Brooksville'),
    ('Bunnell'),
    ('Bushnell'),
    ('Callahan'),
    ('Callaway'),
    ('Cape Canaveral'),
    ('Cape Coral'),
    ('Casselberry'),
    ('Cedar Key'),
    ('Center Hill'),
    ('Century'),
    ('Chattahoochee'),
    ('Chiefland'),
    ('Chipley'),
    ('Cinco Bayou'),
    ('Clearwater'),
    ('Clermont'),
    ('Clewiston'),
    ('Cocoa'),
    ('Cocoa Beach'),
    ('Coconut Creek'),
    ('Coleman'),
    ('Cooper City'),
    ('Coral Gables'),
    ('Coral Springs'),
    ('Cottondale'),
    ('Crescent City'),
    ('Crestview'),
    ('Cross City'),
    ('Crystal River'),
    ('Cutler Bay'),
    ('Dade City'),
    ('Dania Beach'),
    ('Davenport'),
    ('Davie'),
    ('Daytona Beach'),
    ('Daytona Beach Shores'),
    ('De Bary'),
    ('DeFuniak Springs'),
    ('Deerfield Beach'),
    ('Deland'),
    ('Delray Beach'),
    ('Deltona'),
    ('Destin'),
    ('Doral'),
    ('Dunedin'),
    ('Dunnellon'),
    ('Edgewater'),
    ('Edgewood'),
    ('El Portal'),
    ('Estero'),
    ('Esto'),
    ('Eustis'),
    ('Everglades City'),
    ('Fanning Springs'),
    ('Fellsmere'),
    ('Fernandina Beach'),
    ('Flagler Beach'),
    ('Florida City'),
    ('Fort Lauderdale'),
    ('Fort Meade'),
    ('Fort Myers'),
    ('Fort Myers Beach'),
    ('Fort Pierce'),
    ('Fort Walton Beach'),
    ('Fort White'),
    ('Freeport'),
    ('Frostproof'),
    ('Fruitland Park'),
    ('Gainesville'),
    ('Glen Saint Mary'),
    ('Golden Beach'),
    ('Golf'),
    ('Grant-Valkaria'),
    ('Green Cove Springs'),
    ('Greenacres'),
    ('Greensboro'),
    ('Greenville'),
    ('Gretna'),
    ('Groveland'),
    ('Gulf Breeze'),
    ('Gulfport'),
    ('Haines City'),
    ('Hallandale Beach'),
    ('Hampton'),
    ('Havana'),
    ('Haverhill'),
    ('Hawthorne'),
    ('Hialeah'),
    ('Hialeah Gardens'),
    ('High Springs'),
    ('Highland Beach'),
    ('Highland Park'),
    ('Hilliard'),
    ('Hillsboro Beach'),
    ('Holly Hill'),
    ('Hollywood'),
    ('Holmes Beach'),
    ('Homestead'),
    ('Howey-in-the-Hills'),
    ('Hypoluxo'),
    ('Indialantic'),
    ('Indian Creek'),
    ('Indian Harbour Beach'),
    ('Indian River Shores'),
    ('Indian Shores'),
    ('Indiantown'),
    ('Inglis'),
    ('Interlachen'),
    ('Inverness'),
    ('Islamorada, Village of Islands'),
    ('Jacksonville'),
    ('Jacksonville Beach'),
    ('Jasper'),
    ('Jay'),
    ('Juno Beach'),
    ('Jupiter'),
    ('Jupiter Inlet Colony'),
    ('Jupiter Island'),
    ('Kenneth City'),
    ('Key Biscayne'),
    ('Key Colony Beach'),
    ('Key West'),
    ('Keystone Heights'),
    ('Kissimmee'),
    ('La Crosse'),
    ('LaBelle'),
    ('Lady Lake'),
    ('Lake Alfred'),
    ('Lake Buena Vista'),
    ('Lake Butler'),
    ('Lake City'),
    ('Lake Clark Shores'),
    ('Lake Hamilton'),
    ('Lake Helen'),
    ('Lake Mary'),
    ('Lake Park'),
    ('Lake Placid'),
    ('Lake Wales'),
    ('Lake Worth Beach'),
    ('Lakeland'),
    ('Lantana'),
    ('Largo'),
    ('Lauderdale Lakes'),
    ('Lauderdale-By-The-Sea'),
    ('Lauderhill'),
    ('Layton'),
    ('Lazy Lake'),
    ('Lee'),
    ('Leesburg'),
    ('Lighthouse Point'),
    ('Live Oak'),
    ('Longboat Key'),
    ('Longwood'),
    ('Loxahatchee Groves'),
    ('Lynn Haven'),
    ('Macclenny'),
    ('Madeira Beach'),
    ('Madison'),
    ('Maitland'),
    ('Malabar'),
    ('Manalapan'),
    ('Mangonia Park'),
    ('Marathon'),
    ('Marco Island'),
    ('Margate'),
    ('Marianna'),
    ('Mary Esther'),
    ('Mascotte'),
    ('McIntosh'),
    ('Medley'),
    ('Melbourne'),
    ('Melbourne Beach'),
    ('Melbourne Village'),
    ('Mexico Beach'),
    ('Miami'),
    ('Miami Beach'),
    ('Miami Gardens'),
    ('Miami Lakes'),
    ('Miami Shores'),
    ('Miami Springs'),
    ('Micanopy'),
    ('Midway'),
    ('Milton'),
    ('Minneola'),
    ('Miramar'),
    ('Monticello'),
    ('Montverde'),
    ('Moore Haven'),
    ('Mount Dora'),
    ('Mulberry'),
    ('Naples'),
    ('Neptune Beach'),
    ('New Port Richey'),
    ('New Smyrna Beach'),
    ('Newberry'),
    ('Niceville'),
    ('North Bay Village'),
    ('North Lauderdale'),
    ('North Miami'),
    ('North Miami Beach'),
    ('North Palm Beach'),
    ('North Port'),
    ('North Redington Beach'),
    ('Oak Hill'),
    ('Oakland'),
    ('Oakland Park'),
    ('Ocala'),
    ('Ocean Breeze'),
    ('Ocean Ridge'),
    ('Ocoee'),
    ('Okeechobee'),
    ('Oldsmar'),
    ('Opa-locka'),
    ('Orange City'),
    ('Orange Park'),
    ('Orchid'),
    ('Orlando'),
    ('Ormond Beach'),
    ('Oviedo'),
    ('Pahokee'),
    ('Palatka'),
    ('Palm Bay'),
    ('Palm Beach'),
    ('Palm Beach Gardens'),
    ('Palm Beach Shores'),
    ('Palm Coast'),
    ('Palm Shores'),
    ('Palm Springs'),
    ('Palmetto'),
    ('Palmetto Bay'),
    ('Panama City'),
    ('Panama City Beach'),
    ('Parker'),
    ('Parkland'),
    ('Paxton'),
    ('Pembroke Park'),
    ('Pembroke Pines'),
    ('Penney Farms'),
    ('Pensacola'),
    ('Perry'),
    ('Pierson'),
    ('Pinecrest'),
    ('Pinellas Park'),
    ('Plant City'),
    ('Plantation'),
    ('Polk City'),
    ('Pomona Park'),
    ('Pompano Beach'),
    ('Ponce Inlet'),
    ('Port Orange'),
    ('Port Richey'),
    ('Port St. Joe'),
    ('Port St. Lucie'),
    ('Punta Gorda'),
    ('Quincy'),
    ('Reddick'),
    ('Redington Beach'),
    ('Redington Shores'),
    ('Riviera Beach'),
    ('Rockledge'),
    ('Royal Palm Beach'),
    ('Safety Harbor'),
    ('San Antonio'),
    ('Sanford'),
    ('Sanibel'),
    ('Sarasota'),
    ('Satellite Beach'),
    ('Sebastian'),
    ('Sebring'),
    ('Sewall''s Point'),
    ('Shalimar'),
    ('Sneads'),
    ('Sopchoppy'),
    ('South Bay'),
    ('South Daytona'),
    ('South Miami'),
    ('South Palm Beach'),
    ('South Pasadena'),
    ('Southwest Ranches'),
    ('Springfield'),
    ('St. Augustine'),
    ('St. Augustine Beach'),
    ('St. Cloud'),
    ('St. Leo'),
    ('St. Lucie Village'),
    ('St. Marks'),
    ('St. Pete Beach'),
    ('St. Petersburg'),
    ('Starke'),
    ('Stuart'),
    ('Sunny Isles Beach'),
    ('Sunrise'),
    ('Surfside'),
    ('Sweetwater'),
    ('Tallahassee'),
    ('Tamarac'),
    ('Tampa'),
    ('Tarpon Springs'),
    ('Tavares'),
    ('Temple Terrace'),
    ('Tequesta'),
    ('Titusville'),
    ('Treasure Island'),
    ('Trenton'),
    ('Umatilla'),
    ('Valparaiso'),
    ('Venice'),
    ('Vero Beach'),
    ('Virginia Gardens'),
    ('Waldo'),
    ('Wachula'),
    ('Webster'),
    ('Welaka'),
    ('Wellington'),
    ('West Melbourne'),
    ('West Miami'),
    ('West Palm Beach'),
    ('West Park'),
    ('Westlake'),
    ('Weston'),
    ('Wewahitchka'),
    ('White Springs'),
    ('Wildwood'),
    ('Wilton Manors'),
    ('Windermere'),
    ('Winter Garden'),
    ('Winter Haven'),
    ('Winter Park'),
    ('Winter Springs'),
    ('Yankeetown'),
    ('Zephyrhills'),
    ('Zolfo Springs')
) AS m(name)
WHERE s.code = 'FL'
ON CONFLICT (state_id, name) DO NOTHING;
